# Generated by Django 6.0.3 on 2026-05-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місто')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='lab2.city', verbose_name='Звідки')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ends', to='lab2.city', verbose_name='Куди')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=150, verbose_name='ПІБ Пасажира')),
                ('departure_date', models.DateTimeField(verbose_name='Дата та час виїзду')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab2.route', verbose_name='Рейс')),
            ],
        ),
    ]
